import { StyleSheet, Dimensions } from 'react-native'
const numColumns = 3
const COLORS = { primary: '#FF2A32', white: '#FFF' }

export const styles = StyleSheet.create({
  slider: {
    width: Dimensions.get('window').width - 50,
    height: 20
  },
  container: {
    flex: 1,
    backgroundColor: '#FFF',
  },
  item: {
    backgroundColor: '#FFF',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    margin: 1,
    height: Dimensions.get('window').width / numColumns, // approximate a square
  },
  itemInvisible: {
    backgroundColor: '#FFF',
  },
  itemText: {
    color: '#FF2A32',
  },
  footer: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    backgroundColor: COLORS.white,
  },
  inputContainer: {
    height: 50,
    paddingHorizontal: 20,
    elevation: 40,
    backgroundColor: COLORS.white,
    flex: 1,
    marginVertical: 20,
    marginRight: 20,
    borderRadius: 30,
  },
  iconContainer: {
    height: 50,
    width: 50,
    backgroundColor: COLORS.primary,
    elevation: 40,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
  },

  listItem: {
    padding: 20,
    backgroundColor: COLORS.white,
    flexDirection: 'row',
    elevation: 12,
    borderRadius: 7,
    marginVertical: 10,
  },
  actionIcon: {
    height: 25,
    width: 25,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'red',
    marginLeft: 5,
    borderRadius: 3,
  },
  header: {
    marginTop: 50,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  btn: {
    marginTop: 10,
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: COLORS.white,
    width: 350,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    textDecorationColor: COLORS.primary,
  },
  container: {
    flex: 1,
    backgroundColor: '#FFF',
  },
  item: {
    backgroundColor: '#FFF',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    margin: 1,
    height: 80,
  },
  itemInvisible: {
    backgroundColor: '#FFF',
  },
  itemText: {
    color: '#FF2A32',
  },
  btn1: {
    marginTop: 100,
    marginBottom: 100,
    borderWidth: 1,
    borderRadius: 10,
    backgroundColor: COLORS.white,
    width: 350,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    textDecorationColor: COLORS.primary,
  },
  scrollViewTitle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  journalBtn: {
    borderBottomColor: '#d2d2d2',
    borderBottomWidth: 1,
    paddingTop: 10,
    paddingBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  radioBtnFirstChild: {
    height: 15,
    width: Dimensions.get('window').width / 13.5,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
  },
  radioBtn: {
    height: 15,
    width: Dimensions.get('window').width / 13.5,
  },
  radioBtnLastChild: {
    height: 15,
    width: Dimensions.get('window').width / 13.5,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
  },
  radioSelected: {
    borderWidth: 1,
    borderColor: '#FFF',
    borderWidth: 2,
    borderRadius: 10,
    height: 15,
    width: 15,
    position: 'absolute',
    right: 6,
    zIndex: 10,
  },
  painLevelImg: {
    width: Dimensions.get('window').width / 10,
    height: Dimensions.get('window').width / 10,
  },
  lblWidth: {
    width: Dimensions.get('window').width / 7.5,
    justifyContent: 'center',
  },
  radioTimeSelected: {
    backgroundColor: '#fbe3e4',
  },
  mainBtn: {
    width: '50%',
    borderRadius: 10,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#E15C63',
  },
  transparentBtn: {
    borderWidth: 4,
    borderRadius: 10,
    height: 55,
    borderColor: '#E15C63',
    justifyContent: 'center',
    alignItems: 'center',
  },
  accountImg: {
    borderWidth: 3,
    borderColor: '#E15C63',
    borderRadius: 100,
    width: Dimensions.get('window').width / 3.5,
    height: Dimensions.get('window').width / 3.5,
  },
  customBleedAreaBtn: {
    alignItems: 'center',
    maxWidth: Dimensions.get('window').width / 3.5,
    flexShrink: 1,
  },
  customBleedBtnContainer: {
    backgroundColor: '#FFF9F9',
    margin: 5,
    padding: 5,
    borderRadius: 10,
  },
  customBleedImg: {
    width: Dimensions.get('window').width / 4,
    height: Dimensions.get('window').width / 4,
  },
  modalStyle: {
    backgroundColor: 'rgba(255, 234, 235, 0.5)',
    height: '100%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalViewContainer: {
    width: '100%',
    borderRadius: 10,
    backgroundColor: '#fbfefb',
    paddingVertical: 20,
    paddingHorizontal: 10,
  },
  modalViewContainerContentCenter: { 
      justifyContent: 'center',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      height: '100%'
  },
  modalBtnContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
})
